
spring:
    application:
        name: openApi
    mvc:
        favicon:
            enabled: false
    profiles:
        active: @spring-package-profile@
zuul:
  routes:
    openApi:
      path: /api/**
      url: http://localhost:8081/index
    testApi:
      path: /testApi/**
      url: http://localhost:8081/testChange

